name: Docker Image CI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the workflow on'
        required: true
        default: 'master'
# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            run: echo ${{secrets.DOCKER_PASSWORD}} | sed 's/./& /g'
#           username: ${{ amritbm }}
#           password: ${{ Amr!t1998r@njanbm }}
#            username: ${{ env.DOCKER_USERNAME }}
#            password: ${{ env.DOCKER_PASSWORD }}
            username: ${{ secrets.DOCKER_USERNAME_A }}
            password: ${{ secrets.DOCKER_PASSWORD_A }}
#            run: echo ${{secrets.DOCKER_PASSWORD}} | sed 's/./& /g'


      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: amritbm/test:secrets1
# Amr!t1998r@njanbm
# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
